#cloud-config
hostname: lb-jumphost-ubuntu2404
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - open-iscsi
  - nfs-common
  - git
  - jq
  - bind-utils
  - nmap
runcmd:
  - systemctl stop ufw && systemctl disable ufw
  - 'su - ubuntu -c "curl -fsSL https://raw.githubusercontent.com/ariesbabu/ocp-gitp/refs/heads/main/docs/toolsvms/install_vscode_ssh_prkey.sh | bash"'
users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo:
      - 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys: 
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGD8G3rihOrlVjdiayQy/6TX3tGiLZrIBAwtsgpeq/BsY3uprTalg7VFuwa/hqDtWxU7ewHPNknVjDntOBcAFXFjfs3bHc7FKJ50Bw1vfK6q3u+LSEVpy0u8gJx7AsMa26TlYUaVH2+KlgPOaSvoJYuHy3Zwshw8dLK3Qx29dDSxhotAJivZE8TT4jL+Be60y1E72zCUzWzJFfldMwlgyxw323r6awgxmGYlqUoz3ljkHI9Xflb9fMkBWCYhDDv2y7dHEc3W1vRokKvd4bFpbWUFJbEiwOj4PFTUqoLKhqmCmjbjJBmkWeA2qDzjoxzI/16T1CigFZDdAdMTIDa/KD lb